name: weather
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  
  # UI & Icons
  cupertino_icons: ^1.0.8
  lottie: ^3.1.2
  
  # State Management
  provider: ^6.1.2
  equatable: ^2.0.5
  dartz: ^0.10.1
  
  # Networking
  http: ^1.2.2
  
  # Location Services
  geolocator: ^13.0.2
  geocoding: ^3.0.0
  
  # Storage
  shared_preferences: ^2.3.3
  
  # Charts & Visualization
  fl_chart: ^0.69.0
  
  # UI Components & Utilities
  intl: ^0.19.0
  flutter_animate: ^4.5.0
  
  # Icons & Assets
  flutter_launcher_icons: ^0.14.1 

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: 


flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/AppIcon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/AppIcon.png"
    background_color: "#000000"
    theme_color: "#ff0054"
  windows:
    generate: true
    image_path: "assets/AppIcon.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/AppIcon.png"


flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/icons/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
